troika/campus/forms.py
# -*- coding: utf-8 -*-
from flask_wtf import Form
from wtforms import IntegerField, StringField, TextField
from wtforms.validators import DataRequired, Length

from .models import Campus


class CampusForm(Form):

    id = IntegerField()
    name = StringField(
        'Name',
        validators=[DataRequired(message=u'Поле обязательно для заполнения'),
                    Length(min=1, max=128)])
    address = StringField(
        'Address',
        validators=[DataRequired(message=u'Поле обязательно для заполнения'),
                    Length(min=3, max=128)])

    zip = StringField(
        'Zip',
        validators=[Length(min=0, max=16)])

    def __init__(self, *args, **kwargs):
        super(CampusForm, self).__init__(*args, **kwargs)

    def validate(self):
        initial_validation = super(CampusForm, self).validate()
        if not initial_validation:
            return False

        return True

troika/card/forms.py
# -*- coding: utf-8 -*-
from flask_wtf import Form
from wtforms import IntegerField, StringField, TextField
from wtforms.validators import DataRequired, Length

from .models import Card


class CardForm(Form):

    id = IntegerField()
    hard_id = StringField(
        'Hard ID',
        validators=[DataRequired(message=u'Поле обязательно для заполнения'),
                    Length(min=3, max=128)])
    troika_id = StringField(
        'Troika ID',
        validators=[DataRequired(message=u'Поле обязательно для заполнения'),
                    Length(min=3, max=128)])
    name_ru = TextField(u'Название на русском', validators=[Length(min=0, max=300)])
    name_en = TextField(u'Название на англиском', validators=[Length(min=0, max=300)])
    troika_state = IntegerField(u'Статус в Тройке')
    status = StringField(u'Статус')
    campus_id = IntegerField(u'Кампус')

    def __init__(self, *args, **kwargs):
        super(CardForm, self).__init__(*args, **kwargs)

    def validate(self):
        initial_validation = super(CardForm, self).validate()
        if not initial_validation:
            return False

        try:
            self.id.data
        except:
            self.id.data = 0

        card = Card.query.filter(
            (Card.hard_id == self.hard_id.data) |
            (Card.troika_id == self.troika_id.data)).first()
        if card.id != self.id.data:
            self.hard_id.errors.append(u"Карта с таким набором параметров уже есть в базе")
            self.troika_id.errors.append(u"Карта с таким набором параметров уже есть в базе")
            return False
        return True

troika/order/forms.py
# -*- coding: utf-8 -*-
from flask_wtf import Form
from wtforms import IntegerField, StringField, TextField
from wtforms.validators import DataRequired


class OrderForm(Form):

    id = IntegerField()
    user_id = IntegerField('Mobispot user id', validators=[DataRequired()])
    user_email = StringField('Mobispot user email', validators=[DataRequired()])
    image = TextField('Order macket image')
    photo = TextField('Order original photo')
    logo = TextField('Order original logo')
    name = StringField('Order user name')
    position = StringField('Order user position')

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)

    def validate_csrf_token(self, field):
        pass

troika/user/forms.py
# -*- coding: utf-8 -*-
from flask_wtf import Form
from wtforms import PasswordField, TextField
from wtforms.validators import DataRequired, Email, Length

from .models import User


class LoginForm(Form):
    email = TextField(
        'Email',
        validators=[DataRequired(message=u'Поле обязательно для заполнения'),
                    Email(),
                    Length(min=6, max=40)])
    password = PasswordField(
        'Password',
        validators=[DataRequired(message=u'Поле обязательно для заполнения'),
                    Length(min=6, max=40)])

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        initial_validation = super(LoginForm, self).validate()
        if not initial_validation:
            return False

        self.user = User.query.filter_by(email=self.email.data).first()
        if not self.user or not self.user.check_password(self.password.data):
            self.email.errors.append(u'Пользователь не найден')
            self.password.errors.append(u'Пароль не верен')
            return False

        if self.user.status != User.STATUS_ACTIVE:
            self.email.errors.append(u'Пользователь не активирован или заблокирован')
            return False
        return True

troika/__init__.py
# -*- coding: utf-8 -*-
import logging
from troika.app import create_app

from troika.card.models import Card
from troika.history.models import CardsHistory
from troika.order.models import Order
from troika.report.models import Report
from troika.user.models import User
from troika.campus.models import Campus

try:
    from troika.settings_local import Config
except Exception as e:
    logging.exception("Exception: %(body)s", {'body': e})
    from troika.settings import Config

app = create_app(Config)

troika/app.py
# -*- coding: utf-8 -*-
import logging

from flask import Flask, render_template

from troika import card, history, order, public, user, campus
from troika.assets import assets
from troika.extensions import (bcrypt, cache, celery, db, debug_toolbar,
                               login_manager, migrate)

try:
    from troika.settings_local import Config
except Exception as e:
    logging.exception("Exception: %(body)s", {'body': e})
    from troika.settings import Config


def create_app(config_object=Config):

    app = Flask(__name__)
    app.config.from_object(config_object)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app


def register_extensions(app):

    assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    celery.init_app(app)
    return None


def register_blueprints(app):

    app.register_blueprint(card.views.blueprint)
    app.register_blueprint(card.api.blueprint)

    app.register_blueprint(order.views.blueprint)
    app.register_blueprint(order.api.blueprint)

    app.register_blueprint(history.views.blueprint)
    app.register_blueprint(public.views.blueprint)
    app.register_blueprint(user.views.blueprint)
    
    app.register_blueprint(campus.views.blueprint)
    return None


def register_errorhandlers(app):
    def render_error(error):
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template("errors/{0}.html".format(error_code)), error_code
    for errcode in [401, 404, 405, 500]:
        app.errorhandler(errcode)(render_error)
    return None

troika/campus/__init__.py
'''The campus module.'''

from . import views

troika/campus/views.py
# -*- coding: utf-8 -*-
import logging

from flask import (Blueprint, abort, current_app, flash, render_template,
                   request, redirect)
from flask.ext.login import login_required

from troika.campus.models import Campus
from troika.campus.forms import CampusForm

from troika.utils import flash_errors, format_error

logger = logging.getLogger(__name__)

blueprint = Blueprint("campus", __name__, url_prefix='/campus',
                      static_folder="../static")


@blueprint.route("/", methods=['GET'])
@login_required
def list():
    try:
        page = int(request.args.get('page', 1))
    except ValueError:
        abort(404)

    query = Campus.query.order_by('id')

    campuses = query.paginate(page, Campus.PER_PAGE, False)
    return render_template("campus/list.html",
                           campuses=campuses)


@blueprint.route("/new", methods=['GET', 'POST'])
@login_required
def new():

    form = CampusForm(request.form)
    if request.method == 'POST':
        if form.validate():
            campus = Campus()
            form.populate_obj(campus)
            if campus.save():
                flash(u'Данные успешно сохранены', "success")
                return redirect("/campus", code=303)
        else:
            flash_errors(form)

    return render_template("campus/new.html", form=form, campus=form.data)


@blueprint.route("/edit/<int:campus_id>", methods=['GET', 'POST'])
@login_required
def edit(campus_id):

    campus = Campus.query.get(campus_id)
    if not campus:
        abort(404)

    form = CampusForm(request.form)
    if request.method == 'POST':
        form.id.data = campus.id
        if form.validate():
            form.populate_obj(campus)
            if campus.save():
                flash(u'Данные успешно сохранены', "success")
        else:
            flash_errors(form)

    return render_template("campus/edit.html",
                           campus=campus,
                           form=form)


@blueprint.route("/remove/<int:campus_id>", methods=['GET', 'POST'])
@login_required
def remove(campus_id):

    campus = Campus.query.get(campus_id)
    if not campus:
        abort(404)

    if request.method == 'POST':
        id = campus.id
        name = campus.name
        campus.delete()
        flash(u'Кампус %s %s удален' % (id, name), "success")
        return redirect("/campus", code=303)

    return render_template("campus/remove.html", campus=campus)

troika/card/__init__.py
'''The card module.'''

from . import views, api

troika/card/views.py
# -*- coding: utf-8 -*-
import csv
import logging
import json
from grab import Grab

from flask import (Blueprint, abort, current_app, flash, render_template,
                   request, redirect)
from flask.ext.login import current_user, login_required

from troika.card.forms import CardForm
from troika.card.models import Card
from troika.history import tasks
from troika.utils import flash_errors, format_error

logger = logging.getLogger(__name__)

blueprint = Blueprint("card", __name__, url_prefix='/card',
                      static_folder="../static")


@blueprint.route("/", methods=['GET'])
@login_required
def list():
    try:
        page = int(request.args.get('page', 1))
    except ValueError:
        abort(404)

    cards = Card.query.order_by('id desc').paginate(page, Card.PER_PAGE, False)
    return render_template("card/list.html",
                           cards=cards,
                           status_title=Card.STATUS_TITLE,
                           troika_state_title=Card.TROIKA_STATE_TITLE,
                           )


@blueprint.route("/", methods=['POST'])
@login_required
def search():
    try:
        page = int(request.args.get('page', 1))
    except ValueError:
        abort(404)

    search_data = {}
    query = Card.query
    for key in Card.SEARCH_KEYS:
        value = request.form.get(key)
        if value:
            search_data[key] = value
            query = query.filter(getattr(Card, key).like('%' + value + '%'))

    cards = query.order_by('id desc').paginate(page, Card.PER_PAGE, False)
    return render_template("card/list.html",
                           cards=cards,
                           status_title=Card.STATUS_TITLE,
                           troika_state_title=Card.TROIKA_STATE_TITLE,
                           search_data=search_data,)


@blueprint.route("/<int:card_id>", methods=['GET'])
@login_required
def show(card_id):

    card = Card.query.get(card_id)
    if not card:
        abort(404)

    spot_code = u'Не удалось связаться с API Mobispot'
    g = Grab()
    url = '%s/%s/%s' % (current_app.config.get('API_MOBISPOT'),
                        card.SPOT_URL, 
                        card.hard_id)
    g.setup(userpwd=current_app.config.get('AUTH_SIMPLE'))
    g.go(url)

    if g.response.code == 404:
        spot_code = u'N/A'

    if g.response.code == 200:
        response = json.loads(g.response.body)
        if 'code' in response:
            spot_code = response['code']

    return render_template("card/show.html",
                           card=card,
                           status_title=Card.STATUS_TITLE,
                           troika_state_title=Card.TROIKA_STATE_TITLE,
                           campus_title=card.get_campus_title(),
                           spot_code=spot_code)


@blueprint.route("/edit/<int:card_id>", methods=['GET', 'POST'])
@login_required
def edit(card_id):
    card = Card.query.get(card_id)
    if not card:
        abort(404)

    card.old_card = card.to_json()
    form = CardForm(request.form)
    if request.method == 'POST':
        form.id.data = card.id
        if form.validate():
            form.populate_obj(card)
            if card.save():
                flash(u'Данные успешно сохранены', "success")
        else:
            logger.debug('CARD EDIT')
            logger.debug('Request data: %(data)s' % {'data': request.form})
            logger.debug('Form error: %(error)s' %
                         {'error': format_error(form)})

            flash_errors(form)

    return render_template("card/edit.html",
                           card=card,
                           form=form,
                           status_title=card.get_status_title(),
                           troika_state_title=card.get_troika_state_title(),
                           campus_title=card.get_campus_title())


def allowed_file(filename):

    return '.' in filename and \
           filename.rsplit('.', 1)[1] in current_app.config.get(
               'IMPORT_FILE_EXTENSIONS')


def parsing_csv(file):

    csvfile = file.stream.read()
    try:
        dialect = csv.Sniffer().sniff(csvfile)
    except:
        flash(u'Загруженный файл имеет неверный формат.', 'danger')
        return

    cards = []
    reader = csv.reader(csvfile.split('\n'), dialect)
    for row in reader:
        if len(row) < 2:
            continue

        card = Card(row[0], row[1])
        old_card = Card.query.filter(
            (Card.hard_id == card.hard_id) |
            (Card.troika_id == card.troika_id)).first()
        if old_card:
            continue
        cards.append(row)

    return cards


@blueprint.route("/import", methods=['GET', 'POST'])
@login_required
def import_cards():

    if request.method == 'POST':
        file = request.files['importFile']
        if file and allowed_file(file.filename):
            cards = parsing_csv(file)
            if not cards:
                flash(u'Загруженный файл не содержит новых карт.', 'danger')
            else:
                for row in cards:
                    card = Card(row[0], row[1])
                    card.save()

                    tasks.create_action.delay(
                        current_user.id, card.id, card.to_json())

                flash(u'Данные успешно загружены', 'success')

    return render_template("card/import.html")


@blueprint.route("/set_status", methods=['POST'])
@login_required
def set_status():
    card_list = []
    try:
        json_list = json.loads(request.form.get('selected_cards'))
        for item in json_list:
            if int(item) in card_list:
                continue
            card_list.append(int(item))
        troika_status = int(request.form.get('troika_status'))
        status = str(request.form.get('status'))
    except ValueError:
        abort(404)

    cards = Card.query.filter(Card.id.in_(card_list)).all()
    error = 'no'

    for card in cards:
        if troika_status != -1:
            card.troika_state = troika_status
        if status != '-1':
            card.status = status
        if not card.save():
            error = 'yes'

    if error == 'no':
        flash(u'Данные успешно сохранены', "success")

    return redirect("/card", code=303)

troika/history/__init__.py
'''The hoistory module.'''

from . import views

troika/history/views.py
# -*- coding: utf-8 -*-
import logging

from flask import Blueprint, abort, render_template, request
from flask.ext.login import login_required

from troika.card.models import Card
from troika.history.models import CardsHistory

logger = logging.getLogger(__name__)

blueprint = Blueprint("history", __name__, url_prefix='/history',
                      static_folder="../static")


@blueprint.route("/", methods=['GET'])
@login_required
def list():

    try:
        page = int(request.args.get('page', 1))
        card_id = int(request.args.get('card_id', 0))
    except ValueError:
        abort(404)

    card = None
    query = CardsHistory.query.order_by('action_date desc')
    if card_id:
        card = Card.query.get(card_id)
        if not card:
            abort(404)

        query = query.filter_by(card_id=card_id)
    history = query.paginate(page, CardsHistory.PER_PAGE, False)
    return render_template("history/list.html",
                           card=card,
                           history=history,
                           action_title=CardsHistory.ACTION_TITLE,
                           card_id=card_id)


@blueprint.route("/<int:history_id>", methods=['GET'])
@login_required
def show(history_id):

    history = CardsHistory.query.get(history_id)
    if not history:
        abort(404)

    return render_template("history/show.html",
                           history=history,
                           to_text=CardsHistory.to_text,
                           action_title=CardsHistory.ACTION_TITLE)

troika/order/__init__.py
'''The order module.'''

from . import views, api

troika/templates/card/_form.html
<form id="cardForm" class="form-horizontal" method="POST">
  {{ form.hidden_tag() }}

  <div class="form-group">
    <label for="inputHardId" class="col-sm-2 control-label">Hard ID *</label>
    <div class="col-sm-4">
    <input type="text" class="form-control" id="inputHardId" 
      name="hard_id" value="{{ card.hard_id }}">
    </div>
  </div>

  <div class="form-group">
    <label for="inputTroikaId" class="col-sm-2 control-label">Тройка ID *</label>
    <div class="col-sm-4">
      <input type="text" class="form-control" id="inputTroikaId" 
        name="troika_id" value="{{ card.troika_id }}">
    </div>
  </div>

  <div class="form-group">
    <label for="inputNameRu" class="col-sm-2 control-label">Название на русском</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="inputNameRu" 
        name="name_ru" value="{{ card.name_ru|default('', true) }}">
    </div>
  </div>

  <div class="form-group">
    <label for="inputNameEn" class="col-sm-2 control-label">Название на англиском</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="inputNameEn" 
        name="name_en" value="{{ card.name_en|default('', true) }}">
    </div>
  </div>

  <div class="form-group">
    <label for="inputNameEn" class="col-sm-2 control-label">Статус в Тройке</label>
    <div class="col-sm-4">
      <select class="form-control" name="troika_state">
        {% for key, value in troika_state_title.iteritems() %}
          <option {% if card.troika_state == key%} selected="selected" {% endif %} value="{{ key }}">{{ value }}</option>
        {% endfor %}
      </select>
    </div>
  </div>

  <div class="form-group">
    <label for="inputNameEn" class="col-sm-2 control-label">Статус</label>
    <div class="col-sm-4">
      <select class="form-control" name="status">
        {% for key, value in status_title.iteritems() %}
          <option {% if card.status == key%} selected="selected" {% endif %} value="{{ key }}">{{ value }}</option>
        {% endfor %}
      </select>
    </div>
  </div>    

  <div class="form-group">
    <label for="inputCampus" class="col-sm-2 control-label">Кампус</label>
    <div class="col-sm-4">
      <select class="form-control" name="campus_id">
        <option {% if not card.campus_id %} selected="selected" {% endif %} value="0"></option>
        {% for key, value in campus_title.iteritems() %}
          <option {% if card.campus_id == key%} selected="selected" {% endif %} value="{{ key }}">{{ value }}</option>
        {% endfor %}
      </select>
    </div>
  </div>   
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-primary">Сохранить</button>
    </div>
  </div>
</form>

troika/templates/card/edit.html
{% extends "layout.html" %}

{% block page_title %}Тройка > Карты > Редактирование ({{ card.hard_id }}){% endblock %}

{% block breadcrumb %}
  <ol class="breadcrumb">
    <li><a href="/">Главная</a></li>
    <li><a href="/card/">Карты</a></li>
    <li class="active">Редактирование ({{ card.hard_id }})</li>
  </ol>
{% endblock %}
  
{% block content %}
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{ message }}
        </div>
        {% endfor %}
      </div>
    </div>
    {% endif %}
  {% endwith %}

  {% include 'card/_form.html' %}
  
{% endblock %}

troika/templates/card/import.html
{% extends "layout.html" %}

{% block page_title %}Тройка > Карты > Импорт{% endblock %}

{% block menu %}
    <div class="row">
      <div class="col-md-12">
        <ol class="breadcrumb">
        <li><a href="/">Главная</a></li>
        <li><a href="/card/">Карты</a></li>
        <li class="active">Импорт</li>
      </ol>
      </div>
    </div>
{% endblock %}

{% block content %}
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{ message }}
        </div>
        {% endfor %}
      </div>
    </div>
    {% endif %}
  {% endwith %}

  <div class="bs-callout bs-callout-info">
    <p>На данной странице вы можете зарузить файл, 
      данные из которого будут импортированны в систему.</p>

    <p>Загружаемый файл должен быть csv, содержащий набор строк 
      <strong>Hard ID</strong>, <strong>Тройка ID</strong> (являются обязательными)<br /> 
      <strong>Название на русском</strong> и <strong>Название на англиском</strong> (необязательные поля).</p>

    <p>Загружены будут только те карты которые имеют уникаьные <strong>Hard ID</strong>, <strong>Тройка ID</strong>.</p>
  </div>

  <div class="row">
    <div class="col-md-12">
      <form id="importForm" class="form-inline" enctype="multipart/form-data" method="POST">
        <div class="form-group">
          <label for="inputFile">Выберите файл для загрузки</label>
        </div>
        <div class="form-group">
          <input type="file" id="inputFile" name="importFile">
        </div>
        <button type="submit" class="btn btn-primary">Импортировать</button>
      </form>
    </div>
  </div>
{% endblock %}

troika/templates/card/list.html
{% extends "layout.html" %}

{% block page_title %}Тройка > Список карт{% endblock %}

{% block menu %}
  <div class="row">
    <div class="col-md-10">
      <ol class="breadcrumb">
        <li><a href="/">Главная</a></li>
        <li class="active">Карты</li>
      </ol>
    </div>
    <div class="col-md-2 text-right">
      <a href="javascript:;"
        class="btn btn-primary btn-sm" id="show-filters" title="Фильтр">
        <span class="glyphicon glyphicon glyphicon-search" aria-hidden="true">
        </span>
      </a>
      <a href="javascript:;"
        class="btn btn-primary btn-sm" id="show-statuses" title="Редактировать статус">
        <span class="glyphicon glyphicon-edit" aria-hidden="true">
        </span>
      </a>
      <a href="{{ url_for('card.import_cards') }}"
        class="btn btn-primary btn-sm" title="Импорт">
        <span class="glyphicon glyphicon glyphicon-import" aria-hidden="true">
        </span>
      </a>
    </div>
  </div>
{% endblock %}

{% block content %}
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{ message }}
        </div>
        {% endfor %}
      </div>
    </div>
    {% endif %}
  {% endwith %}

  <div class="row filters-block {% if not search_data %}filters-block_hide{% endif %}">
    <div class="col-md-10">
      <form class="form-horizontal" role="form" method="POST">
        <div class="form-group">
          <label class="control-label col-sm-2" for="hard_id">Hard ID:</label>
          <div class="col-sm-5">
            <input type="text" class="form-control"
              pattern=".{0}|.{3,}" title="Минимум 3 символа"
              name="hard_id" id="hard_id"
              {% if 'hard_id' in search_data %}
                value="{{ search_data['hard_id'] }}"
              {% endif %}>
          </div>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-2" for="troika_id">Тройка ID:</label>
          <div class="col-sm-5">
            <input type="text" class="form-control"
              pattern=".{0}|.{3,}" itle="Минимум 3 символа"
              name="troika_id" id="troika_id"
              {% if 'troika_id' in search_data %}
                value="{{ search_data['troika_id'] }}"
              {% endif %}>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <button type="reset" class="btn btn-default">Сбросить</button>
            <button type="submit" class="btn btn-default">Найти</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  
  <div class="row statuses-block statuses-block-hide">
    <div class="col-md-10">
      <form class="form-horizontal" role="form" method="POST" action="/card/set_status">
        <div class="form-group">
          <label class="control-label col-sm-2" for="set_troika_status">Статус в Тройке:</label>
          <div class="col-sm-5">
            <select class="form-control" name="troika_status" id="set_troika_status">
            <option value="-1" selected="selected">Не менять</option>
            {% for key, value in troika_state_title.iteritems() %}
              <option value="{{ key }}">{{ value }}</option>
            {% endfor %}
            </select>
          </div>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-2" for="set_status">Статус:</label>
          <div class="col-sm-5">
            <select class="form-control" name="status" id="set_status">
            <option value="-1" selected="selected">Не менять</option>
            {% for key, value in status_title.iteritems() %}
              <option value="{{ key }}">{{ value }}</option>
            {% endfor %}
            </select>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <input type="hidden" value="{}" name="selected_cards" id="selected_cards">
            <button id="save_statuses" type="submit" class="btn btn-default">Сохранить</button>
          </div>
        </div>
      </form>
    </div>
  </div>    
    
  <table class="table table-bordered table-responsive">
      <thead>
        <tr>
          <th></th>
          <th>Hard ID</th>
          <th>Тройка ID</th>
          <th>Статус в Тройке</th>
          <th>Статус</th>
          <th class="col-md-1"></th>
        </tr>
      </thead>
      <tbody>
        {% for card in cards.items %}
          <tr>
            <td class="text-center"><input card_id="{{ card.id }}" class="card-checkbox" type="checkbox"></td>
            <td>
              <a href="{{ url_for('card.show', card_id=card.id) }}">
                {{ card.hard_id }}
              </a>
            </td>
            <td>{{ card.troika_id }}</td>
            <td>{{ troika_state_title[card.troika_state] }}</td>
            <td>{{ status_title[card.status] }}</td>
            <td>
              <a href="{{ url_for('card.edit', card_id=card.id) }}" class="btn btn-primary btn-sm" title="Редактировать">
                <span class="glyphicon glyphicon-edit" aria-hidden="true">
                </span>
              </a>
              <a href="{{ url_for('history.list') }}?card_id={{ card.id }}"
                class="btn btn-primary btn-sm" title="История изменений">
                <span class="glyphicon glyphicon-list-alt" aria-hidden="true">
                </span>
              </a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    
  {% block pagination %}
    <nav>
      <ul class="pager">
        {% if cards.has_prev %}
        <li>
          <a href="{{ url_for('card.list') }}?page={{ cards.prev_num }}{% if troika_id %}&troika_id={{ troika_id }}{% endif %}">
            Previous
          </a>
        </li>
        {% endif %}
        {% if cards.has_next %}
        <li>
          <a href="{{ url_for('card.list') }}?page={{ cards.next_num }}{% if troika_id %}&troika_id={{ troika_id }}{% endif %}">
            Next
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
  {% endblock %}
{% endblock %}

troika/templates/card/show.html
{% extends "layout.html" %}

{% block page_title %}Тройка > Карт > Просмотр ({{ card.hard_id }}){% endblock %}

{% block breadcrumb %}
  <ol class="breadcrumb">
    <li><a href="/">Главная</a></li>
    <li><a href="/card/">Карты</a></li>
    <li class="active">Просмотр ({{ card.hard_id }})</li>
  </ol>
{% endblock %}
  
{% block content %}
  <table class="table table-bordered table-responsive">
    <thead>
      <tr>
        <th class="col-md-2">Attribute</th>
        <th>Value</th>
      </tr>
    </thead>
    <tbody>
      <tr><td>Hard ID</td><td>{{ card.hard_id }}</td></tr>
      <tr><td>Тройка ID</td><td>{{ card.troika_id }}</td></tr>
      <tr><td>Название на русском</td><td>{{ card.name_ru|default('N/A', true) }}</td></tr>
      <tr><td>Название на английском</td><td>{{ card.name_en|default('N/A', true) }}</td></tr>
      <tr><td>Дата добавления</td><td>{{ card.creation_date }}</td></tr>
      <tr><td>Статус в Тройке</td><td>{{ troika_state_title[card.troika_state] }}</td></tr>
      <tr><td>Статус</td><td>{{ status_title[card.status] }}</td></tr>
      <tr>
        <td>Кампус</td>
        <td>
          {% for key, value in campus_title.iteritems() %}
            {% if card.campus_id == key%}
              {{ value }}
            {% endif %}
          {% endfor %}
        </td>
      </tr>
      <tr>
         <td>Код активации</td>
         <td>{{ spot_code }}</td>
      </tr>
    </tbody>
  </table>
  <p>
    <a href="{{ url_for('history.list') }}?card_id={{ card.id }}" class="btn btn-primary" title="История изменений">
      История изменений
    </a>
    <a href="{{ url_for('card.edit', card_id=card.id) }}" class="btn btn-primary" title="Редактировать">
      Редактировать
    </a>
  </p>
{% endblock %}